import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { cookies } from "next/headers";
import { geistMono, geistSans, roboto_slab } from "@/lib/fonts";

export const metadata: Metadata = {
   title: "ScholarShip",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const cookieStore = await cookies();
   const theme = cookieStore.get("theme")?.value ?? "light";
   return (
      <html lang="en" className={theme === "dark" ? "dark" : ""}>
         <body
            className={`${geistSans.variable} ${geistMono.variable} ${roboto_slab.variable} antialiased dark:bg-neutral-700 bg-gray-100 text-neutral-700 dark:text-white`}
         >
            <main>
               <SessionProvider>{children}</SessionProvider>
            </main>
            <Toaster position="top-right" richColors closeButton />
         </body>
      </html>
   );
}
