import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "@/components/menu-custom/menu-custom";
import ButtonDarkMode from "@/components/button-dark-mode/button-dark-mode";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-neutral-700 bg-gray-100 text-neutral-700 dark:text-white`}
         >
            {/* <ButtonDarkMode /> */}
            <main>
               <SessionProvider>{children}</SessionProvider>
            </main>
            <Toaster position="top-right" richColors closeButton />
         </body>
      </html>
   );
}
